[features]
seeds = false
skip-lint = false

[programs.testnet]
tokenizer = "ErCER1skeaeqzRzSaqpmAKEAZmGGdh9VRzNAXXWUXv8f"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.testnet.solana.com"
# cluster = "localnet"
wallet = "/Users/jeffopenpacks/.config/solana/id.json"

[build]
arch = "sbf"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
